//! 秘书Agent核心Traits定义
//! Core Traits Definitions for Secretary Agent
//!
//! 这个模块定义了秘书Agent框架的核心抽象，开发者可以通过实现这些trait
//! This module defines the core abstractions of the Secretary Agent framework, allowing developers to implement these traits
//! 来完全自定义秘书的行为。
//! to fully customize the behavior of the secretary.
//!
//! ## 核心Traits
//! ## Core Traits
//!
//! - [`SecretaryBehavior`][]: 定义秘书的完整行为
//! - [`SecretaryBehavior`][]: Defines the complete behavior of the secretary
//! - [`InputHandler`][]: 处理特定类型的输入
//! - [`InputHandler`][]: Handles specific types of input
//! - [`PhaseHandler`][]: 处理工作流中的某个阶段
//! - [`PhaseHandler`][]: Handles a specific phase within a workflow
//! - [`WorkflowOrchestrator`][]: 编排多阶段工作流
//! - [`WorkflowOrchestrator`][]: Orchestrates multi-phase workflows

use super::error::SecretaryError;
use async_trait::async_trait;
use serde::{Serialize, de::DeserializeOwned};
use std::fmt::Debug;

// =============================================================================
// 消息抽象
// Message Abstractions
// =============================================================================

/// 秘书输入消息Trait
/// Secretary Input Message Trait
///
/// 所有发送给秘书的消息都需要实现这个trait。
/// All messages sent to the secretary must implement this trait.
/// 这允许开发者定义自己的输入消息类型。
/// This allows developers to define their own input message types.
///
/// # 示例
/// # Example
///
/// ```rust,ignore
/// #[derive(Debug, Clone, Serialize, Deserialize)]
/// enum MyInput {
///     TextMessage(String),
///     VoiceCommand { audio_url: String },
///     FileUpload { path: String, mime_type: String },
/// }
///
/// impl SecretaryInput for MyInput {}
/// ```
pub trait SecretaryInput:
    Send + Sync + Clone + Debug + Serialize + DeserializeOwned + 'static
{
}

/// 秘书输出消息Trait
/// Secretary Output Message Trait
///
/// 所有秘书发出的消息都需要实现这个trait。
/// All messages issued by the secretary must implement this trait.
/// 这允许开发者定义自己的输出消息类型。
/// This allows developers to define their own output message types.
///
/// # 示例
/// # Example
///
/// ```rust,ignore
/// #[derive(Debug, Clone, Serialize, Deserialize)]
/// enum MyOutput {
///     TextReply(String),
///     ActionRequired { action: String, options: Vec<String> },
///     Notification { level: String, message: String },
/// }
///
/// impl SecretaryOutput for MyOutput {}
/// ```
pub trait SecretaryOutput:
    Send + Sync + Clone + Debug + Serialize + DeserializeOwned + 'static
{
}

// =============================================================================
// 秘书行为定义
// Secretary Behavior Definition
// =============================================================================

/// 秘书行为Trait - 核心抽象
/// Secretary Behavior Trait - Core Abstraction
///
/// 这是框架最核心的trait，定义了秘书如何响应用户输入。
/// This is the core trait of the framework, defining how the secretary responds to user input.
/// 开发者需要实现这个trait来创建自定义的秘书。
/// Developers need to implement this trait to create custom secretaries.
///
/// # 类型参数
/// # Type Parameters
///
/// - `Input`: 秘书接受的输入类型
/// - `Input`: The input type accepted by the secretary
/// - `Output`: 秘书产生的输出类型
/// - `Output`: The output type generated by the secretary
/// - `State`: 秘书状态类型
/// - `State`: The state type of the secretary
///
/// # 示例
/// # Example
///
/// ```rust,ignore
/// struct MySecretary {
///     name: String,
///     llm: Arc<dyn LLMProvider>,
/// }
///
/// #[async_trait]
/// impl SecretaryBehavior for MySecretary {
///     type Input = MyInput;
///     type Output = MyOutput;
///     type State = MyState;
///
///     async fn handle_input(
///         &self,
///         input: Self::Input,
///         ctx: &mut SecretaryContext<Self::State>,
///     ) -> Result<Vec<Self::Output>, SecretaryError> {
///         match input {
///             MyInput::TextMessage(text) => {
///                 // 处理文本消息
///                 // Process text message
///                 Ok(vec![MyOutput::TextReply(format!("收到: {}", text))])
///             }
///             _ => Ok(vec![]),
///         }
///     }
///
///     fn welcome_message(&self) -> Option<Self::Output> {
///         Some(MyOutput::TextReply(format!("你好，我是{}!", self.name)))
///     }
///
///     fn initial_state(&self) -> Self::State {
///         MyState::new()
///     }
/// }
/// ```
#[async_trait]
pub trait SecretaryBehavior: Send + Sync {
    /// 秘书接受的输入类型
    /// The input type accepted by the secretary
    type Input: SecretaryInput;

    /// 秘书产生的输出类型
    /// The output type generated by the secretary
    type Output: SecretaryOutput;

    /// 秘书的状态类型
    /// The state type of the secretary
    type State: Send + Sync + 'static;

    /// 处理用户输入
    /// Process user input
    ///
    /// 这是秘书的核心方法，当收到用户输入时会调用此方法。
    /// This is the core method of the secretary, called when user input is received.
    /// 返回要发送给用户的输出消息列表。
    /// Returns a list of output messages to be sent to the user.
    ///
    /// # 参数
    /// # Parameters
    ///
    /// - `input`: 用户输入
    /// - `input`: User input
    /// - `ctx`: 秘书上下文，包含状态和共享资源
    /// - `ctx`: Secretary context, containing state and shared resources
    ///
    /// # 返回
    /// # Returns
    ///
    /// 返回要发送给用户的输出消息列表
    /// Returns a list of output messages to be sent to the user
    async fn handle_input(
        &self,
        input: Self::Input,
        ctx: &mut super::context::SecretaryContext<Self::State>,
    ) -> Result<Vec<Self::Output>, SecretaryError>;

    /// 欢迎消息
    /// Welcome message
    ///
    /// 当秘书启动时，可以选择发送一条欢迎消息给用户。
    /// When the secretary starts, it can optionally send a welcome message to the user.
    /// 返回 `None` 表示不发送欢迎消息。
    /// Returning `None` means no welcome message will be sent.
    fn welcome_message(&self) -> Option<Self::Output> {
        None
    }

    /// 初始化状态
    /// Initialize state
    ///
    /// 创建秘书的初始状态
    /// Creates the initial state of the secretary
    fn initial_state(&self) -> Self::State;

    /// 定时检查
    /// Periodic check
    ///
    /// 在事件循环的每次迭代中调用（当没有用户输入时）。
    /// Called in each iteration of the event loop (when there is no user input).
    /// 可以用来检查后台任务、发送提醒等。
    /// Can be used to check background tasks, send reminders, etc.
    ///
    /// 默认实现不做任何事情。
    /// Default implementation does nothing.
    async fn periodic_check(
        &self,
        _ctx: &mut super::context::SecretaryContext<Self::State>,
    ) -> Result<Vec<Self::Output>, SecretaryError> {
        Ok(vec![])
    }

    /// 连接断开时的清理
    /// Cleanup on disconnection
    ///
    /// 当用户连接断开时调用，可以用来保存状态、清理资源等。
    /// Called when the user connection is broken; can be used to save state, clean up resources, etc.
    async fn on_disconnect(
        &self,
        _ctx: &mut super::context::SecretaryContext<Self::State>,
    ) -> Result<(), SecretaryError> {
        Ok(())
    }

    /// 错误处理
    /// Error handling
    ///
    /// 当处理输入时发生错误，调用此方法生成错误响应。
    /// Called to generate an error response when an error occurs during input processing.
    /// 默认实现返回 `None`，表示不向用户发送错误消息。
    /// Default implementation returns `None`, meaning no error message is sent to the user.
    fn handle_error(&self, _error: &SecretaryError) -> Option<Self::Output> {
        None
    }
}

// =============================================================================
// 阶段处理器
// Phase Handler
// =============================================================================

/// 阶段处理器Trait
/// Phase Handler Trait
///
/// 用于实现工作流中的单个阶段。每个阶段接收输入，处理后产生输出。
/// Used to implement a single phase in a workflow. Each phase receives input and produces output after processing.
/// 这允许将复杂的处理逻辑拆分成多个独立的阶段。
/// This allows complex processing logic to be split into multiple independent phases.
///
/// # 类型参数
/// # Type Parameters
///
/// - `Input`: 阶段接收的输入类型
/// - `Input`: Input type received by the phase
/// - `Output`: 阶段产生的输出类型
/// - `Output`: Output type produced by the phase
/// - `State`: 秘书状态类型
/// - `State`: Secretary state type
#[async_trait]
pub trait PhaseHandler<Input, Output, State>: Send + Sync
where
    Input: Send + 'static,
    Output: Send + 'static,
    State: Send + Sync + 'static,
{
    /// 阶段名称（用于日志和调试）
    /// Phase name (for logging and debugging)
    fn name(&self) -> &str;

    /// 处理输入
    /// Handle input
    async fn handle(
        &self,
        input: Input,
        ctx: &mut super::context::SecretaryContext<State>,
    ) -> Result<PhaseResult<Output>, SecretaryError>;

    /// 是否可以跳过此阶段
    /// Whether this phase can be skipped
    fn can_skip(&self, _input: &Input, _ctx: &super::context::SecretaryContext<State>) -> bool {
        false
    }
}

/// 阶段处理结果
/// Phase processing result
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum PhaseResult<T> {
    /// 继续下一阶段
    /// Continue to next phase
    Continue(T),
    /// 需要用户输入后继续
    /// Need user input before continuing
    NeedInput {
        /// 当前结果（部分完成）
        /// Current result (partially completed)
        partial_result: Option<T>,
        /// 请求用户输入的提示
        /// Prompt for user input
        prompt: String,
    },
    /// 跳过后续阶段
    /// Skip subsequent phases
    Skip,
    /// 终止处理
    /// Abort processing
    Abort { reason: String },
}

// =============================================================================
// 工作流编排
// Workflow Orchestration
// =============================================================================

/// 工作流编排器Trait
/// Workflow Orchestrator Trait
///
/// 用于编排多个阶段处理器，实现复杂的工作流。
/// Used to orchestrate multiple phase handlers to implement complex workflows.
#[async_trait]
pub trait WorkflowOrchestrator<Input, Output, State>: Send + Sync
where
    Input: Send + 'static,
    Output: Send + 'static,
    State: Send + Sync + 'static,
{
    /// 工作流名称
    /// Workflow name
    fn name(&self) -> &str;

    /// 执行工作流
    /// Execute workflow
    async fn execute(
        &self,
        input: Input,
        ctx: &mut super::context::SecretaryContext<State>,
    ) -> Result<WorkflowResult<Output>, SecretaryError>;
}

/// 工作流执行结果
/// Workflow execution result
#[derive(Debug, Clone)]
#[non_exhaustive]
pub enum WorkflowResult<T> {
    /// 工作流完成
    /// Workflow completed
    Completed(T),
    /// 需要用户输入
    /// Need user input
    NeedInput(String),
    /// 工作流被跳过
    /// Workflow skipped
    Skipped,
    /// 工作流被终止
    /// Workflow aborted
    Aborted(String),
}

// =============================================================================
// 输入处理器
// Input Handler
// =============================================================================

/// 输入处理器Trait
/// Input Handler Trait
///
/// 用于处理特定类型的用户输入。可以注册多个处理器来处理不同类型的输入。
/// Used to handle specific types of user input. Multiple handlers can be registered for different input types.
#[async_trait]
pub trait InputHandler<Input, Output, State>: Send + Sync
where
    Input: Send + 'static,
    Output: Send + 'static,
    State: Send + Sync + 'static,
{
    /// 处理器名称
    /// Handler name
    fn name(&self) -> &str;

    /// 检查是否可以处理此输入
    /// Check if this input can be handled
    fn can_handle(&self, input: &Input) -> bool;

    /// 处理输入
    /// Handle input
    async fn handle(
        &self,
        input: Input,
        ctx: &mut super::context::SecretaryContext<State>,
    ) -> Result<Vec<Output>, SecretaryError>;
}

// =============================================================================
// 事件监听器
// Event Listener
// =============================================================================

/// 秘书内部事件
/// Secretary internal event
#[derive(Debug)]
#[non_exhaustive]
pub enum SecretaryEvent<State> {
    /// 秘书启动
    /// Secretary started
    Started,
    /// 秘书停止
    /// Secretary stopped
    Stopped,
    /// 收到用户输入
    /// User input received
    InputReceived,
    /// 发送了输出
    /// Output sent
    OutputSent,
    /// 状态变更
    /// State changed
    StateChanged,
    /// 自定义事件
    /// Custom event
    Custom(String),
    /// 占位符（用于类型约束）
    /// Placeholder (used for type constraints)
    #[doc(hidden)]
    _Phantom(std::marker::PhantomData<State>),
}

/// 事件监听器Trait
/// Event Listener Trait
///
/// 可以监听秘书的内部事件，用于日志、监控、扩展等。
/// Can listen to internal events of the secretary for logging, monitoring, extensions, etc.
#[async_trait]
pub trait EventListener<State>: Send + Sync
where
    State: Send + Sync + 'static,
{
    /// 监听器名称
    /// Listener name
    fn name(&self) -> &str;

    /// 处理事件
    /// Handle event
    async fn on_event(
        &self,
        event: &SecretaryEvent<State>,
        ctx: &super::context::SecretaryContext<State>,
    );
}

// =============================================================================
// 中间件
// Middleware
// =============================================================================

/// 中间件Trait
/// Middleware Trait
///
/// 可以在输入处理前后执行额外逻辑，如日志、认证、限流等。
/// Can execute extra logic before and after input processing, such as logging, authentication, rate limiting, etc.
#[async_trait]
pub trait Middleware<Input, Output, State>: Send + Sync
where
    Input: Send + Clone + 'static,
    Output: Send + 'static,
    State: Send + Sync + 'static,
{
    /// 中间件名称
    /// Middleware name
    fn name(&self) -> &str;

    /// 输入预处理
    /// Input preprocessing
    ///
    /// 在处理输入之前调用。返回 `None` 表示不拦截，继续处理。
    /// Called before processing input. Returning `None` means no interception, proceed with processing.
    /// 返回 `Some(outputs)` 表示拦截输入，直接返回这些输出。
    /// Returning `Some(outputs)` means intercept the input and return these outputs directly.
    async fn before_handle(
        &self,
        _input: &Input,
        _ctx: &super::context::SecretaryContext<State>,
    ) -> Option<Vec<Output>> {
        None
    }

    /// 输出后处理
    /// Output post-processing
    ///
    /// 在产生输出后调用。可以修改或过滤输出。
    /// Called after producing output. Can modify or filter the outputs.
    async fn after_handle(
        &self,
        _input: &Input,
        outputs: Vec<Output>,
        _ctx: &super::context::SecretaryContext<State>,
    ) -> Vec<Output> {
        outputs
    }
}

// =============================================================================
// 便捷实现
// Convenient Implementation
// =============================================================================

/// 为所有满足约束的类型自动实现 SecretaryInput
/// Automatically implement SecretaryInput for all types that satisfy the constraints
impl<T> SecretaryInput for T where
    T: Send + Sync + Clone + Debug + Serialize + DeserializeOwned + 'static
{
}

/// 为所有满足约束的类型自动实现 SecretaryOutput
/// Automatically implement SecretaryOutput for all types that satisfy the constraints
impl<T> SecretaryOutput for T where
    T: Send + Sync + Clone + Debug + Serialize + DeserializeOwned + 'static
{
}

// =============================================================================
// 测试
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use serde::{Deserialize, Serialize};

    #[derive(Debug, Clone, Serialize, Deserialize)]
    enum TestInput {
        Text(String),
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    enum TestOutput {
        Reply(String),
    }

    // 验证自动实现的 trait
    // Verify auto-implemented traits
    fn _assert_input_impl<T: SecretaryInput>() {}
    fn _assert_output_impl<T: SecretaryOutput>() {}

    #[test]
    fn test_auto_impl() {
        _assert_input_impl::<TestInput>();
        _assert_output_impl::<TestOutput>();
    }
}
