[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hello-world"
version = "0.1.1"
description = "A simple hello-world template"
readme = "README.md"
license = {text = "MIT License"}
authors = [
    {name = "Cheng Chen", email = "chenzi00103@gmail.com"},
]
dependencies = [
    "pyarrow>=5.0.0",
    "mofa-core",
]

[project.scripts]
hello-world = "hello_world.main:main"

[tool.setuptools.packages.find]
include = ["hello_world*"]
