[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{cookiecutter.agent_name}}"
version = "{{cookiecutter.version}}"
description = "{{cookiecutter.description}}"
readme = "README.md"
license = {text = "MIT License"}
authors = [
    {%- for author in cookiecutter.authors.split(',') %}
    {name = "{{ author.strip() }}"}{%- if not loop.last %},{% endif -%}
    {%- endfor %}
]
dependencies = [
    "pyarrow>=5.0.0",
]

[project.scripts]
{{cookiecutter.agent_name}} = "{{cookiecutter.agent_name}}.main:main"

[tool.setuptools.packages.find]
include = ["{{cookiecutter.agent_name}}*"]

