[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "terminal-input"
version = "0.3.6"
description = "Dora terminal input"
readme = "README.md"
license = {text = "MIT License"}
authors = [
    {name = "Haixuan Xavier Tao", email = "tao.xavier@outlook.com"},
    {name = "Enzo Le Van", email = "dev@enzo-le-van.fr"},
]
dependencies = [
    "numpy<2.0.0",
    "pyarrow>=5.0.0",
]

[project.scripts]
terminal-input = "terminal_input.main:main"

[tool.setuptools.packages.find]
include = ["terminal_input*"]
